import AVFoundation
import os

/// Synthesized orb sounds. No asset files: one AVAudioEngine with a single AVAudioSourceNode,
/// all tones generated by sample counting inside the render block.
final class SoundEngine {
    static let shared: SoundEngine = SoundEngine()

    private let synth: OrbSynth = OrbSynth()
    private var engine: AVAudioEngine? = nil
    private var sourceNode: AVAudioSourceNode? = nil
    private var sessionConfigured: Bool = false

    private init() {}

    /// Optional: start the engine ahead of the first press so the buildup has no startup latency.
    func warmUp() {
        _ = ensureRunning()
    }

    /// Tone gliding 180Hz -> 520Hz over exactly `duration` seconds (pass OrbTiming.hold).
    func startBuildup(duration: Double) {
        guard ensureRunning() else { return }
        synth.sendBuild(.start(max(0.05, duration)))
    }

    /// Fast (~50ms) release of the buildup tone.
    func stopBuildup() {
        synth.sendBuild(.stop)
    }

    /// One ~160ms pop (880Hz -> 120Hz with a transient tick). Also stops any buildup.
    func pop() {
        guard ensureRunning() else { return }
        synth.sendPop()
    }

    // MARK: - Engine

    private func configureSessionIfNeeded() {
        if sessionConfigured { return }
        sessionConfigured = true
        let session = AVAudioSession.sharedInstance()
        try? session.setCategory(.ambient, mode: .default, options: [])
        try? session.setActive(true)
    }

    private func ensureRunning() -> Bool {
        if let running = engine, running.isRunning {
            return true
        }
        configureSessionIfNeeded()

        let eng: AVAudioEngine
        if let existing = engine {
            eng = existing
        } else {
            let created = AVAudioEngine()
            let hardwareRate: Double = created.outputNode.outputFormat(forBus: 0).sampleRate
            let rate: Double = hardwareRate > 0 ? hardwareRate : 44100
            let maybeFormat: AVAudioFormat? = AVAudioFormat(standardFormatWithSampleRate: rate, channels: 1)
            guard let format = maybeFormat else { return false }
            synth.setSampleRate(rate)

            let synthRef: OrbSynth = synth
            let node = AVAudioSourceNode(format: format, renderBlock: { (isSilence, _, frameCount, audioBufferList) -> OSStatus in
                synthRef.render(isSilence: isSilence, frameCount: frameCount, bufferList: audioBufferList)
                return noErr
            })
            created.attach(node)
            created.connect(node, to: created.mainMixerNode, format: format)
            sourceNode = node
            engine = created
            eng = created
        }

        do {
            eng.prepare()
            try eng.start()
            return true
        } catch {
            return false
        }
    }
}

/// Minimal os_unfair_lock wrapper; the lock lives in a stable heap allocation.
final class SynthLock: @unchecked Sendable {
    private let pointer: UnsafeMutablePointer<os_unfair_lock_s>

    init() {
        pointer = UnsafeMutablePointer<os_unfair_lock_s>.allocate(capacity: 1)
        pointer.initialize(to: os_unfair_lock_s())
    }

    deinit {
        pointer.deinitialize(count: 1)
        pointer.deallocate()
    }

    func lock() { os_unfair_lock_lock(pointer) }
    func unlock() { os_unfair_lock_unlock(pointer) }
    func tryLock() -> Bool { return os_unfair_lock_trylock(pointer) }
}

/// Synth state. The main thread only posts commands under the lock; the render thread takes
/// them with a non-blocking tryLock at the start of each buffer and owns all DSP state.
final class OrbSynth: @unchecked Sendable {
    enum BuildCommand {
        case none
        case start(Double)
        case stop
    }

    private let lock: SynthLock = SynthLock()

    // Shared (guarded by lock)
    private var pendingBuild: BuildCommand = .none
    private var pendingPop: Bool = false
    private var pendingFastStop: Bool = false

    // Render-thread only
    private var sampleRate: Double = 44100
    private var buildActive: Bool = false
    private var buildSample: Double = 0
    private var buildDurationSamples: Double = 1
    private var buildPhase: Double = 0
    private var buildAmp: Double = 0
    private var buildTarget: Double = 0
    private var buildReleaseStep: Double = 0
    private var popActive: Bool = false
    private var popSample: Double = 0
    private var popPhase: Double = 0
    private var noiseState: UInt32 = 0x9E3779B9

    private let buildLevel: Double = 0.18
    private let popLevel: Double = 0.5
    private let popLength: Double = 0.16

    /// Called once, before the engine starts.
    func setSampleRate(_ rate: Double) {
        sampleRate = rate
    }

    func sendBuild(_ command: BuildCommand) {
        lock.lock()
        pendingBuild = command
        lock.unlock()
    }

    func sendPop() {
        lock.lock()
        pendingBuild = .stop
        pendingFastStop = true
        pendingPop = true
        lock.unlock()
    }

    // MARK: - Render thread

    func render(isSilence: UnsafeMutablePointer<ObjCBool>, frameCount: AVAudioFrameCount, bufferList: UnsafeMutablePointer<AudioBufferList>) {
        takePendingCommands()

        let buffers = UnsafeMutableAudioBufferListPointer(bufferList)
        let frames: Int = Int(frameCount)

        if !buildActive && !popActive {
            for buffer in buffers {
                if let data = buffer.mData {
                    memset(data, 0, Int(buffer.mDataByteSize))
                }
            }
            isSilence.pointee = ObjCBool(true)
            return
        }

        for frame in 0..<frames {
            var s: Double = 0
            if buildActive {
                s += nextBuildSample()
            }
            if popActive {
                s += nextPopSample()
            }
            let out = Float(tanh(s))
            for buffer in buffers {
                guard let data = buffer.mData else { continue }
                let capacity: Int = Int(buffer.mDataByteSize) / MemoryLayout<Float>.size
                if frame < capacity {
                    data.assumingMemoryBound(to: Float.self)[frame] = out
                }
            }
        }
    }

    private func takePendingCommands() {
        guard lock.tryLock() else { return }
        let build: BuildCommand = pendingBuild
        let pop: Bool = pendingPop
        let fast: Bool = pendingFastStop
        pendingBuild = .none
        pendingPop = false
        pendingFastStop = false
        lock.unlock()

        switch build {
        case .none:
            break
        case .start(let duration):
            // Keep phase and current amplitude continuous so a restart never clicks.
            buildActive = true
            buildSample = 0
            buildDurationSamples = max(1, duration * sampleRate)
            buildTarget = buildLevel
        case .stop:
            buildTarget = 0
            let releaseTime: Double = fast ? 0.012 : 0.05
            buildReleaseStep = buildLevel / (releaseTime * sampleRate)
        }

        if pop {
            popActive = true
            popSample = 0
            popPhase = 0
        }
    }

    private func nextBuildSample() -> Double {
        if buildAmp < buildTarget {
            let attackStep: Double = buildLevel / (0.03 * sampleRate)
            buildAmp = min(buildTarget, buildAmp + attackStep)
        } else if buildAmp > buildTarget {
            buildAmp = max(buildTarget, buildAmp - max(buildReleaseStep, 1e-6))
        }
        if buildAmp <= 0 && buildTarget <= 0 {
            buildAmp = 0
            buildActive = false
            return 0
        }

        let p: Double = min(1, buildSample / buildDurationSamples)
        buildSample += 1
        // Exponential glide 180 -> 520Hz, holds at 520 after `duration`.
        let freq: Double = 180 * pow(520.0 / 180.0, p)
        buildPhase += freq / sampleRate
        if buildPhase >= 1 { buildPhase -= 1 }

        let x: Double = 2 * Double.pi * buildPhase
        let h2: Double = 0.45 * p
        let h3: Double = 0.28 * p * p
        let h4: Double = 0.18 * p * p * p
        let v: Double = sin(x) + h2 * sin(2 * x) + h3 * sin(3 * x) + h4 * sin(4 * x)
        let norm: Double = 1 + 0.6 * (h2 + h3 + h4)
        return buildAmp * v / norm
    }

    private func nextPopSample() -> Double {
        let t: Double = popSample / sampleRate
        if t >= popLength {
            popActive = false
            return 0
        }
        popSample += 1

        // Fast exponential pitch drop 880 -> 120Hz over 70ms, then holds.
        let freq: Double = 880 * pow(120.0 / 880.0, min(1, t / 0.07))
        popPhase += freq / sampleRate
        if popPhase >= 1 { popPhase -= 1 }

        let attack: Double = min(1, t / 0.0015)
        let decay: Double = exp(-t / 0.035)
        let window: Double = 1 - t / popLength
        let env: Double = attack * decay * window
        let x: Double = 2 * Double.pi * popPhase
        var s: Double = popLevel * env * (sin(x) + 0.3 * sin(2 * x)) / 1.3

        // Crisp transient tick: ~3ms of fast-decaying noise.
        if t < 0.004 {
            s += 0.35 * nextNoise() * exp(-t / 0.0007)
        }
        return s
    }

    private func nextNoise() -> Double {
        var x: UInt32 = noiseState
        x ^= x << 13
        x ^= x >> 17
        x ^= x << 5
        noiseState = x
        return Double(x) / 2147483647.5 - 1
    }
}
